INSERT INTO sections (title, subtitle, description, image_url, tag_name, active, sort_order) VALUES
  ('RVS', 'Formation professionnelle', 'Programmes de formation et développement des compétences.', 'https://pub-03ee1d270877480c8234daba55734fbe.r2.dev/fcra-sitweb/sections/section_1763461443825_rvs_image.jpg', 'Education', true, 3),
  ('Educations', 'Éducation : semer aujourd’hui, construire demain', 'Au FCRA, l’éducation est une priorité absolue. Convaincu que le savoir est un levier fondamental pour le développement individuel et collectif, le FCRA s’engage à offrir un enseignement de qualité à tous les niveaux, dans un cadre alliant rigueur, bienveillance et excellence.', 'https://pub-03ee1d270877480c8234daba55734fbe.r2.dev/fcra-sitweb/sections/section_1763461448658_educations_image.png', 'Education', true, 2),
  ('RELIGION', 'La spiritualité occupe une place centrale au sein de notre centre, où chaque année, de nombreux événements religieux rassemblent fidèles, familles et communautés dans un esprit de partage, de foi et de solidarité.', 'Parmi les temps forts, le mois sacré du Ramadan est un moment particulièrement symbolique. À cette occasion, notre centre organise de vastes actions sociales : plus de 10 000 repas sont servis chaque jour dans plus de dix communes dans la capitale, offrant ainsi soutien et réconfort aux plus démunis.', 'https://pub-03ee1d270877480c8234daba55734fbe.r2.dev/fcra-sitweb/sections/section_1763461452355_religion_image.jpg', NULL, true, 5),
  ('Orphelinat', 'Actuellement, plus de 230 enfants — filles et garçons — bénéficient d’un accompagnement global au sein de nos structures : hébergement, alimentation, soins, éducation et encadrement affectif.', 'Notre engagement envers les orphelins.

Au cœur des actions du FCRA, l’accueil et la prise en charge des orphelins occupent une place essentielle. À Madagascar, nous gérons quatre centres d’orphelinat situés à Antaniavo, Andakana, Manakara et Sakoana, offrant un refuge sûr, stable et bienveillant à des enfants privés de soutien familial.

Actuellement, plus de 230 enfants — filles et garçons — bénéficient d’un accompagnement global au sein de nos structures : hébergement, alimentation, soins, éducation et encadrement affectif. Chaque centre est pensé comme un véritable foyer, où les enfants peuvent s’épanouir, apprendre et se construire un avenir digne et prometteur. 

Notre objectif est simple mais fondamental : redonner à chaque enfant la sécurité, la dignité et l’amour dont il a besoin pour grandir sereinement.

', 'https://pub-03ee1d270877480c8234daba55734fbe.r2.dev/fcra-sitweb/sections/section_1763461455783_orphelinat_image.jpg', 'Communauté', true, 1),
  ('SANTE', 'Santé : des soins accessibles pour tous', 'Parce que le développement passe aussi par la santé, le FCRA s’engage à faciliter l’accès aux soins de qualité pour les populations les plus vulnérables à Madagascar. À travers plusieurs structures médicales, ouvertes à tous, l''association répond aux besoins essentiels des communautés, dans un esprit de solidarité, d’humanité et de professionnalisme.', 'https://pub-03ee1d270877480c8234daba55734fbe.r2.dev/fcra-sitweb/sections/section_1763461458879_sante_image.png', NULL, true, 4),
  ('Enseignement supérieur', 'Enseignement supérieur – Un tremplin vers l’excellence académique', 'Enseignement supérieur – Un tremplin vers l’excellence académique

Au-delà de la formation technique, le FCRA s’engage à soutenir l’accès équitable à l’enseignement supérieur, convaincu que chaque jeune mérite une chance de poursuivre ses études, quelle que soit son origine.

', 'https://pub-03ee1d270877480c8234daba55734fbe.r2.dev/fcra-sitweb/sections/section_1763461461865_enseignement_sup_rieur_image.jpg', NULL, true, 7),
  ('INFOPRO', 'INFOPRO – Institut de Formation Professionnelle', 'Dans le prolongement de ses actions éducatives, le FCRA a mis en place l’Institut de Formation Professionnelle (INFOPRO) afin de répondre aux besoins concrets des jeunes en quête d’autonomie et d’insertion professionnelle.', 'https://pub-03ee1d270877480c8234daba55734fbe.r2.dev/fcra-sitweb/sections/section_1763461465917_infopro_image.jpg', NULL, true, 6);