// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjtvrqozrbbxathbofyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqdHZycW96cmJieGF0aGJvZnl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NDM1OTksImV4cCI6MjA2NzIxOTU5OX0.47JRlp9wgcmw5PW0ArRclbI7pnG5kkP7Ed7Eqi86dCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});